<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DefaultModule\Module'    => __DIR__ . '/Module.php',
  'Default_Bootstrap'       => __DIR__ . '/Bootstrap.php',
  'Default_IndexController' => __DIR__ . '/src/controllers/IndexController.php',
  'Default_ErrorController' => __DIR__ . '/src/controllers/ErrorController.php',
  'Default_HelpController'  => __DIR__ . '/src/controllers/HelpController.php',
);
