<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'scripts/index/link-noauth'            => __DIR__ . '/src/views/scripts/index/link-noauth.phtml',
    'scripts/index/posta-interna'          => __DIR__ . '/src/views/scripts/index/posta-interna.phtml',
    'scripts/index/posta-vigilfuoco'       => __DIR__ . '/src/views/scripts/index/posta-vigilfuoco.phtml',
    'scripts/index/procedure-web'          => __DIR__ . '/src/views/scripts/index/procedure-web.phtml',
    'scripts/index/info'                   => __DIR__ . '/src/views/scripts/index/info.phtml',
    'scripts/index/posta-certificata'      => __DIR__ . '/src/views/scripts/index/posta-certificata.phtml',
    'scripts/index/turnario'               => __DIR__ . '/src/views/scripts/index/turnario.phtml',
    'scripts/index/_login'                 => __DIR__ . '/src/views/scripts/index/_login.phtml',
    'scripts/index/link-utili'             => __DIR__ . '/src/views/scripts/index/link-utili.phtml',
    'scripts/index/rubrica-voip'           => __DIR__ . '/src/views/scripts/index/rubrica-voip.phtml',
    'scripts/index/index'                  => __DIR__ . '/src/views/scripts/index/index.phtml',
    'scripts/index/rubrica-interna'        => __DIR__ . '/src/views/scripts/index/rubrica-interna.phtml',
    'scripts/index/posta-dipartimentale'   => __DIR__ . '/src/views/scripts/index/posta-dipartimentale.phtml',
    'scripts/index/password-dimenticata'   => __DIR__ . '/src/views/scripts/index/password-dimenticata.phtml',
    'scripts/index/rubrica-dipartimentale' => __DIR__ . '/src/views/scripts/index/rubrica-dipartimentale.phtml',
    'scripts/index/piani-emergenza'        => __DIR__ . '/src/views/scripts/index/piani-emergenza.phtml',
    'scripts/error/error'                  => __DIR__ . '/src/views/scripts/error/error.phtml',
    'scripts/help/index'                   => __DIR__ . '/src/views/scripts/help/index.phtml',
);
