<h1>Hai problemi di accesso?</h1>

<!--Per il dominio <b>vigilfuoco.it</b> le credenziali di accesso sono le stesse della <b>posta elettronica vigilfuoco.it</b>.
<br />
Se la password è stata <b>dimenticata</b> la si può reimpostare al seguente link: <a href="https://intranet.dipvvf.it/registrazioneutenti/resetPwd.aspx" target="_blank">Reset Password</a>
<br />
Se la password è <b>scaduta</b> occorre impostare la nuova password al seguente link: <a href="https://intranet.dipvvf.it/registrazioneutenti/pwdScaduta.aspx" target="_blank">Password scaduta</a>
<br /><br /> -->

Per il dominio <b>no.dipvvf.it</b> le credenziali di accesso sono le stesse utilizzate all'<b>avvio del PC</b> o per l'<b>accesso ad Internet</b>.
<br /> <br />
<b>N.B.</b> Il Nome utente va digitato senza <b>"NO\"</b> iniziale.
<br />Se la password è stata <b>dimenticata</b> contattare il supporto informatico del Comando al 0321/4406225