<h1>Piani di emergenza</h1>

<a href="#GallerieFaraggiana">Piano Gallerie FF.SS. di Faraggiana</a><br />
<a href="#GallerieVaralloPombia">Piano Gallerie FF.SS. di Varallo Pombia (<b>CIRCA 2,7 KM)</b></a><br />
<a href="#GallerieCascineCarrataStorninaGattico">Piano Gallerie FF.SS. di Cascine d'Enea - La Carrata - Stornina e Gattico</a><br />
<a href="#A26">Piano A26</a><br />
<a href="#Neve">Piano Neve</a><br />
<a href="#RicercaPersoneScomparse">Piano Ricerca Persone Scomparse</a><br />
<a href="#SARPOM">Piano Interno SARPOM</a><br />
<a href="#BALCHEM">Piano Esterno Balchem</a><br />
<a href="#RADICICHIMICA">Piano Esterno Radici Chimica</a><br />
<a href="#POLOSMARTINOTRECATE">Piano Esterno Polo Industriale San Martino di Trecate</a><br />
<a href="#MATERIERADIOTATTIVE">Procedura di Emergenza Trasporto Materie Radioattive e Fissili</a><br />

<br /><br />
<hr />
<br /><br />

<a name="GallerieFaraggiana">Piano Gallerie FF.SS. di Faraggiana</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_gallerie_ferroviarie_faraggiana/PEI_FARAGGIANA_2013.pdf') ?>" target="_blank">PEI_FARAGGIANA_2013.pdf</a><br />
       
<br /><br />

<a name="GallerieVaralloPombia">Piano Gallerie FF.SS. di Varallo Pombia (<b>CIRCA 2,7 KM)</b></a> <br />

<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_gallerie_ferroviarie_varallo/01-104A.3.2.21 Varallo P_PEI_Revisione_101117.pdf') ?>" target="_blank">01-104A.3.2.21 Varallo P_PEI_Revisione_101117.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_gallerie_ferroviarie_varallo/02-104A.3.2.21 Varallo P_PEI-Copertine Allegati_101117.pdf') ?>" target="_blank">02-104A.3.2.21 Varallo P_PEI-Copertine Allegati_101117.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_gallerie_ferroviarie_varallo/03-104A.3.2.21 Varallo P_PEI-ALL 2A_101117.pdf') ?>" target="_blank">03-104A.3.2.21 Varallo P_PEI-ALL 2A_101117.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_gallerie_ferroviarie_varallo/04-104A.3.2.21 Varallo P_PEI-All 2B_101117.pdf') ?>" target="_blank">04-104A.3.2.21 Varallo P_PEI-All 2B_101117.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_gallerie_ferroviarie_varallo/05-104A.3.2.21 Varallo P_PEI-All 2C_101117.pdf') ?>" target="_blank">05-104A.3.2.21 Varallo P_PEI-All 2C_101117.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_gallerie_ferroviarie_varallo/06-104A.3.2.21 Varallo P_PEI-All 3_101117.pdf') ?>" target="_blank">06-104A.3.2.21 Varallo P_PEI-All 3_101117.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_gallerie_ferroviarie_varallo/07-104A.3.2.21 Varallo P_PEI-All 4 Flusso A_101117.pdf') ?>" target="_blank">07-104A.3.2.21 Varallo P_PEI-All 4 Flusso A_101117.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_gallerie_ferroviarie_varallo/08-104A.3.2.21 Varallo P_PEI-All 4 Flusso B_101117.pdf') ?>" target="_blank">08-104A.3.2.21 Varallo P_PEI-All 4 Flusso B_101117.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_gallerie_ferroviarie_varallo/09-104A.3.2.21 Varallo P_PEI-All 4 Flusso C_101117.pdf') ?>" target="_blank">09-104A.3.2.21 Varallo P_PEI-All 4 Flusso C_101117.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_gallerie_ferroviarie_varallo/10-104A.3.2.21 Varallo P_PEI-All 4 Flusso D_101117.pdf') ?>" target="_blank">10-104A.3.2.21 Varallo P_PEI-All 4 Flusso D_101117.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_gallerie_ferroviarie_varallo/11-104A.3.2.21 Varallo P_PEI-All 4 Flusso E_101117.pdf') ?>" target="_blank">11-104A.3.2.21 Varallo P_PEI-All 4 Flusso E_101117.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_gallerie_ferroviarie_varallo/12-104A.3.2.21 Varallo P_PEI-All 4 Flusso F_101117.pdf') ?>" target="_blank">12-104A.3.2.21 Varallo P_PEI-All 4 Flusso F_101117.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_gallerie_ferroviarie_varallo/13-104A.3.2.21 Varallo P_PEI-All 4 Note_101117.pdf') ?>" target="_blank">13-104A.3.2.21 Varallo P_PEI-All 4 Note_101117.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_gallerie_ferroviarie_varallo/14-104A.3.2.21 Varallo P_PEI-All 5_101117.pdf') ?>" target="_blank">14-104A.3.2.21 Varallo P_PEI-All 5_101117.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_gallerie_ferroviarie_varallo/15-104A.3.2.21 Varallo P_PEI-All 6_101117.pdf') ?>" target="_blank">15-104A.3.2.21 Varallo P_PEI-All 6_101117.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_gallerie_ferroviarie_varallo/16-104A.3.2.21 Varallo P_PEI-All 7_101117.pdf') ?>" target="_blank">16-104A.3.2.21 Varallo P_PEI-All 7_101117.pdf</a><br />
       

<br /><br />

<a name="GallerieCascineCarrataStorninaGattico">Piano Gallerie FF.SS. di Cascine d'Enea - La Carrata - Stornina e Gattico</a> <br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_gallerie_cascine/PEI_CASCINE_D_ENEA_CARRATA_STORNINA_REV1.PDF') ?>" target="_blank">01_PEI_CASCINE_D_ENEA_CARRATA_STORNINA_REV1.PDF</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_gallerie_cascine/GALLERIA_GATTICO_REV1.PDF') ?>" target="_blank">02_GALLERIA_GATTICO_REV1.PDF</a><br />

<br /><br />

<a name="A26">Piano A26</a> <br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_A26/Piano_gestione_emergenza_DT1-A26_NO_ rev_01.pdf') ?>" target="_blank">01_Piano_gestione_emergenza_DT1-A26_NO_ rev_01.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_A26/QUADRO_CONOSCITIVO_BOSCAROLA_rev_1A.pdf') ?>" target="_blank">02_QUADRO_CONOSCITIVO_BOSCAROLA_rev_1A.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_A26/QUADRO_CONOSCITIVO_MASSINO_VISCONTI_rev_01A.pdf') ?>" target="_blank">03_QUADRO_CONOSCITIVO_MASSINO_VISCONTI_rev_01A.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_A26/QUADRO_CONOSCITIVO_S_IGINO_rev_1a.pdf') ?>" target="_blank">04_QUADRO_CONOSCITIVO_S_IGINO_rev_1a.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_A26/QUADRO_CONOSCITIVO_VALSESIA_rev_1A.pdf') ?>" target="_blank">05_QUADRO_CONOSCITIVO_VALSESIA_rev_1A.pdf</a><br />

<br /><br />

<a name="Neve">Piano Neve</a> <br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_neve/01_PIANO_NEVE_DA_CONSULTARE.doc') ?>" target="_blank">01_PIANO_NEVE_DA_CONSULTARE.doc</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_neve/02_A26_Manuale_operazione_invernali.doc') ?>" target="_blank">02_A26_Manuale_operazione_invernali.doc</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_neve/03_A26_Allegati_al_Manuale_2009-10.ppt') ?>/public/documents/" target="_blank">03_A26_Allegati_al_Manuale_2009-10.ppt</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_neve/04_A26_Schemi_allegati_al_Manuale_2009-10.pdf') ?>" target="_blank">04_A26_Schemi_allegati_al_Manuale_2009-10.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_neve/05_A4_Piano_neve.doc') ?>" target="_blank">05_A4_Piano_neve.doc</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_neve/06_A4_Novara_est.jpg') ?>" target="_blank">06_A4_Novara_est.jpg</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_neve/07_A4_Carisio.jpg') ?>" target="_blank">07_A4_Carisio.jpg</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_neve/08_A4_Rondissone.jpg') ?>" target="_blank">08_A4_Rondissone.jpg</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_neve/09_A4_Greggio.jpg') ?>" target="_blank">09_A4_Greggio</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_neve/10_ANAS_Piano_emergenza_neve.doc') ?>" target="_blank">10_ANAS_Piano_emergenza_neve.doc</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_neve/11_ANAS_Cartografia.pdf') ?>" target="_blank">11_ANAS_Cartografia.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_neve/12_A8_Piano_neve.doc') ?>" target="_blank">12_A8_Piano_neve.doc</a><br />

<br /><br />

<a name="RicercaPersoneScomparse">Piano Ricerca Persone Scomparse</a> <br />                   
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_ricerca_persone_scomparse/piano_provinciale_rps.pdf') ?>" target="_blank">Piano Provinciale R.P.S</a><br />

<br /><br />
<a name="SARPOM">Piano Interno SARPOM</a> <br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/00-PIANO_DEMERGENZA INTERNO_-_11PEI29228Rev10_E03.pdf') ?>" target="_blank">PIANO D'EMERGENZA INTERNO.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/01-Allegato_PEI01_Verbale_consultazione.pdf') ?>" target="_blank">01-Allegato_PEI01_Verbale_consultazione.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/02-Allegato_PEI02_Recapiti.pdf') ?>" target="_blank">02-Allegato_PEI02_Recapiti.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/03-Allegato_PEI03_MSDS.pdf') ?>" target="_blank">03-Allegato_PEI03_MSDS.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/04-Allegato_PEI04_Scenari.pdf') ?>" target="_blank">04-Allegato_PEI04_Scenari.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/05-01-Allegato_PEI05_Piani_demergenza_specifici.pdf') ?>" target="_blank">05-01-Allegato_PEI05_Piani_demergenza_specifici.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/05-02-Allegato_PEI05_All_1.D.1.2_APS2_EIR1.pdf') ?>" target="_blank">05-02-Allegato_PEI05_All_1.D.1.2_APS2_EIR1.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/05-03-Allegato_PEI05_All_1.D.1.2_FCCU_EIR6-SCHD6.pdf') ?>" target="_blank">05-03-Allegato_PEI05_All_1.D.1.2_FCCU_EIR6-SCHD6.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/05-04-Allegato_PEI05_All_1.D.1.2_KERO_EIR4-SCHG4.pdf') ?>" target="_blank">05-04-Allegato_PEI05_All_1.D.1.2_KERO_EIR4-SCHG4.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/05-05-Allegato_PEI05_All_1.D.1.2_LSADO_EIR4-SCHI4.pdf') ?>" target="_blank">05-05-Allegato_PEI05_All_1.D.1.2_LSADO_EIR4-SCHI4.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/05-06-Allegato_PEI05_All_1.D.1.2_TGCU_TOP1-SCHW1.pdf') ?>" target="_blank">05-06-Allegato_PEI05_All_1.D.1.2_TGCU_TOP1-SCHW1.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/05-07-Allegato_PEI05_EIR1-SCHJ1.pdf') ?>" target="_blank">05-07-Allegato_PEI05_EIR1-SCHJ1.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/05-08-Allegato_PEI05_Top_1_SWS-V1.pdf') ?>" target="_blank">05-08-Allegato_PEI05_Top_1_SWS-V1.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/06-Allegato_PEI06_Registrazione_emergenza.pdf') ?>" target="_blank">06-Allegato_PEI06_Registrazione_emergenza.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/07-Allegato_PEI07_Numeri_Telefono_per_lemergenza.pdf') ?>" target="_blank">07-Allegato_PEI07_Numeri_Telefono_per_lemergenza.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/08-Allegato_PEI08_Rapporto_prova_AI.pdf') ?>" target="_blank">08-Allegato_PEI08_Rapporto_prova_AI.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/09-01-Allegato_PEI09_Organigramma.pdf') ?>" target="_blank">09-01-Allegato_PEI09_Organigramma.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/09-02-Allegato_PERTPEI09_Organigramma_Poster.pdf') ?>" target="_blank">09-02-Allegato_PERTPEI09_Organigramma_Poster.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/10-Allegato_PEI10_Compiti.pdf') ?>" target="_blank">10-Allegato_PEI10_Compiti.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/11-Allegato_PEI11_Radio.pdf') ?>" target="_blank">11-Allegato_PEI11_Radio.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/12-Allegato_PEI12_Call_Out.pdf') ?>" target="_blank">12-Allegato_PEI12_Call_Out.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/13-01-A0-16885_-_sorgenti_radioattive_NEW.pdf') ?>" target="_blank">13-01-A0-16885_-_sorgenti_radioattive_NEW.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/13-02-A0-16885_-_sorgenti_radioattive.pdf') ?>" target="_blank">13-02-A0-16885_-_sorgenti_radioattive.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/13-03-A0-16886_-_punti_di_raccolta.pdf') ?>" target="_blank">13-03-A0-16886_-_punti_di_raccolta.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/13-04-A2-16910_CENTRI_DI_COORDINAMENTO_E_CONTROLLO.pdf') ?>" target="_blank">13-04-A2-16910_CENTRI_DI_COORDINAMENTO_E_CONTROLLO.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/13-05-Allegato_PEI13_Planimetrie.pdf') ?>" target="_blank">13-05-Allegato_PEI13_Planimetrie.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/13-06-Planimetria_Antincendio.pdf') ?>" target="_blank">13-06-Planimetria_Antincendio.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/13-07-PS-6028-Antincendio_con_zone.pdf') ?>" target="_blank">13-07-PS-6028-Antincendio_con_zone.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/14-Allegato_PEI14_Centri.pdf') ?>" target="_blank">14-Allegato_PEI14_Centri.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/15-Allegato_PEI15_Piano_Medico.pdf') ?>" target="_blank">15-Allegato_PEI15_Piano_Medico.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/16a-Allegato_PEI16A_Disposizioni_emergenze_sorgenti_radioattive.pdf') ?>" target="_blank">16a-Allegato_PEI16A_Disposizioni_emergenze_sorgenti_radioattive.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/16b-Allegato_PEI16B_Disposizioni_emergenze_strade_esterne_e_ferrovie.pdf') ?>" target="_blank">16b-Allegato_PEI16B_Disposizioni_emergenze_strade_esterne_e_ferrovie.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/17-Allegato_PEI17_Comunicazioni_Esterne.pdf') ?>" target="_blank">17-Allegato_PEI17_Comunicazioni_Esterne.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_sarpom_raffineria_padana_olii_minerali/18-Allegato_PEI18_Assetto_impiantistico_antincendio_e_attrezzature_per_le_emergenze.pdf') ?>" target="_blank">18-Allegato_PEI18_Assetto_impiantistico_antincendio_e_attrezzature_per_le_emergenze.pdf</a><br />

<br /><br />

<a name="BALCHEM">Piano Esterno Balchem</a> <br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_balchem_italia/PEE_BALCHEM.pdf') ?>" target="_blank">PEE_BALCHEM.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_balchem_italia/cartografia generale.pdf') ?>" target="_blank">cartografia generale.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_balchem_italia/ortocartografia_PEE.jpg') ?>" target="_blank">ortocartografia_PEE.jpg</a><br />

<br /><br />

<a name="RADICICHIMICA">Piano Esterno Radici Chimica</a> <br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_radici_chimica/PEE_RADICI_CHIMICA.pdf') ?>" target="_blank">PEE_RADICI_CHIMICA.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_radici_chimica/Allegato_A1_Radici_ultima.pdf') ?>" target="_blank">Allegato_A1_Radici_ultima.pdf</a><br />

<br /><br />

<a name="POLOSMARTINOTRECATE">Piano Esterno Polo Industriale San Martino di Trecate</a> <br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_s_martinodi_trecate/PEE_Polo_industriale_san_martino_trecate.pdf') ?>" target="_blank">PEE_Polo_industriale_san_martino_trecate.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_s_martinodi_trecate/Cartografie_PEE_Trecate_allarme.pdf') ?>" target="_blank">Cartografie_PEE_Trecate_allarme.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_s_martinodi_trecate/Cartografie_PEE_Trecate_preallarme67.pdf') ?>" target="_blank">Cartografie_PEE_Trecate_preallarme67.pdf</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/piano_s_martinodi_trecate/Cartografie_Stabilimento_Tigas26.pdf') ?>" target="_blank">Cartografie_Stabilimento_Tigas26.pdf</a><br />

<br /><br />

<a name="MATERIERADIOTATTIVE">Procedura di Emergenza Trasporto Materie Radioattive e Fissili</a><br />
<a href="<?php echo Utils_File::getDownloadUrl('documents/piani_emergenza/procedure_trasporto_materiale_fissile/procedure_emergenza_trasporto_materie_radioattive_e_fissili.pdf') ?>" target="_blank">procedure_emergenza_trasporto_materie_radioattive_e_fissili.pdf</a><br />


