<h1>Posta interna @no.dipvvf.it</h1>

<img src="/images/webmail_qmail.jpg" class="img_float_left" /> La Posta Interna @no.dipvvf.it, operativa dal 27 Febbraio 2012, nasce al fine di ottimizzare le comunicazioni interne tra i vari uffici, limitando quanto più possibile l'uso della carta. 
<br /><br />
(<i>Per ulteriori informazioni si rimanda all'ODS del 22 Febbraio 2012, nr.54</i>)
<br /><br />

<b>Come accedo?</b>
<br />
La Posta interna è configurabile su <u>Outlook Express</u> e <u>Microsoft Outlook</u>. Per tale configurazione rivolgersi all'Ufficio Informatica.
<br />
E' possibile, inoltre, consultarla via <b>Webmail</b> all'indirizzo <a href="http://posta" target="_blank">http://posta</a>
<br /><br />
<b>A chi posso scrivere?</b>
<br />
Per ottenere un elenco sempre aggiornato delle caselle esistenti è possibile:
<br /><br />
1) consultare la <a href="http://old_www.no.dipvvf.it/servizio_posta.htm#Uffici" target="_self">rubrica Intranet</a><br /> 
2) consultare la <i><u>rubrica Indirizzi</u></i> nella Webmail<br /> 
3) da client di posta interrogare la <b>RUBRICA POSTA INTERNA</b> in base alle seguenti guide: 
<br /><br />
<ul>
<li><a href="<?php echo Utils_File::getDownloadUrl('documents/guide/posta_interna_qmail-outlook_express-interrogare_rubrica_ldap.doc') ?>" target="_blank">Outlook Express</a></li> 
<li><a href="<?php echo Utils_File::getDownloadUrl('documents/guide/posta_interna_qmail-outlook-interrogare_rubrica_ldap.doc') ?>" target="_blank">Microsoft Outlook</a></li> 
</ul>
<br />
<u>N.B. : Per la configurazione della RUBRICA POSTA INTERNA rivolgersi all'Ufficio Informatica</u>

<br /><br />
<b>Chi consulta le caselle?</b>
<br />
Di seguito l'elenco delle caselle di posta esistenti e degli utenti che ne hanno accesso
<br /><br />
<ul>
<li><a href="<?php echo Utils_File::getDownloadUrl('documents/guide/caselle_interne_ed_utenza.xls') ?>" target="_blank">Utenti e Caselle</a></li> 
</ul>

