<h1>Posta Certificata @cert.vigilfuoco.it</h1>

<img src="/images/webmail_pec.jpg" class="img_float_left" /> Le caselle di Posta Certificata attivate nel Comando sono consultabili dal solo personale autorizzato. 
<br /><br /><br /><br /><br />

<b>Come accedo?</b> 
<br /><br /> 
L'accesso avviene tramite Webmail all'indirizzo:
<br /><br />  
<ul>
<li><a href="https://pec.interno.it/webmail/" target="_blank">https://pec.interno.it/webmail/</a></li>
</ul>
<br /><br />  
Le caselle attualmente attivate sono:
<ul>
<li>Comando: com.novara@cert.vigilfuoco.it</li>
<li>Prevenzione: com.prev.novara@cert.vigilfuoco.it</li>
</ul>

