<h1>Posta Dipartimentale @dipvvf.it</h1>

<img src="/images/webmail_dipartimentale.jpg" class="img_float_left" /> Le caselle Dipartimentali hanno valenza solo all'interno del Dipartimento e sono consultabili dal solo personale autorizzato. 
<br /><br /><br /><br />

<b>Come accedo?</b> 
<br /><br /> 
L'accesso avviene tramite Webmail agli indirizzi:
<br /><br />  
<ul>
<li>Sala Operativa: <a href="http://posta.dipvvf.it/novara.so.prov" target="_blank">novara.so.prov@dipvvf.it</a></li>
<li>Comando: <a href="http://posta.dipvvf.it/novara.com.prov" target="_blank">novara.com.prov@dipvvf.it</a></li>
<li>Ced: <a href="http://posta.dipvvf.it/novara.ced" target="_blank">novara.ced@dipvvf.it</a></li>
</ul>
