<h1>Posta Vigilfuoco @vigilfuoco.it</h1>

<img src="/images/webmail_vigilfuoco.jpg" class="img_float_left" /> Le caselle Vigilfuoco sono caselle esterne al comando e hanno valenza nazionale. 
<br /><br /><br /><br /><br />

<b>Come accedo?</b> 
<br /><br /> 
L'accesso avviene tramite Webmail all'indirizzo: <a href="https://webmail.vigilfuoco.it" target="_blank">https://webmail.vigilfuoco.it</a>
<br />
La Webmail è consultabile da qualsiasi luogo esterno al comando.

