<h1>Rubrica interna</h1>
<ul>
<li><b>Codice altoparlante: 7848901</b></li>
<li><a href="http://old_www.no.dipvvf.it/servizio_posta.htm" target="_blank">E-Mail interne</a></li>
<li><a href="<?php echo Utils_File::getDownloadUrl('documents/rubrica/nr_interni.pdf') ?>" target="_blank">Numeri Interni</a></li>
<li><a href="<?php echo Utils_File::getDownloadUrl('documents/rubrica/num-tel.xls') ?>" target="_blank">Telefoni Cellulari in Convenzione</a></li>
<li><a href="<?php echo Utils_File::getDownloadUrl('documents/rubrica/numeri_brevi.pdf') ?>" target="_blank">Numeri brevi</a></li>
<li><a href="<?php echo Utils_File::getDownloadUrl('documents/rubrica/comuni.pdf') ?>" target="_blank">Numeri di Tel. COMUNI</a></li>
<li><a href="<?php echo Utils_File::getDownloadUrl('documents/rubrica/magistrati.pdf') ?>" target="_blank">Numeri di Tel. Magistrati</a></li>
<li><a href="<?php echo Utils_File::getDownloadUrl('documents/rubrica/stampa.xls') ?>" target="_blank">Numeri di Tel. STAMPA - TV - RADIO</a></li>
<li><a href="<?php echo Utils_File::getDownloadUrl('documents/rubrica/enti.pdf') ?>" target="_blank">Numeri di Tel. ENTI VARI</a></li>
</ul>
